// Result report — the printable PDF field document, composed in the browser.
//
// The report is assembled from the *same* objects the answer card renders: the
// answer payload (answer_text, confidence, physics_check, geodetic, trace), the
// georeference block, the drawn AOI and the scene records. Nothing is recomputed
// here and nothing is invented — where the console withholds a value (an
// unlocated scene, a raster that never declared its size) the report says so in
// the same words the UI uses.
//
// Layout is deliberate: light paper, dark ink, serif body text, monospace for
// coordinates and numeric values, so a printed copy reads like a field document
// rather than a screenshot of the dark console. pdf-lib is imported lazily —
// nobody pays for the PDF writer until they ask for a PDF.
//
// The standard PDF fonts are WinAnsi-encoded, so any character outside CP1252
// (σ, ≈, → …) is transliterated before it reaches the page: a report must not
// fail to generate because an answer used a Greek letter.

import {
  PROVENANCE,
  aoiAreaHa,
  aoiAreaKm2,
  extentKm,
  fmtLat,
  fmtLon,
  gsdLabel,
  isGeoreferenced,
  placeSummary,
  utmBlock,
  withheldGeodetic
} from './geo.js';
import { ABSTAIN_GATE } from './model.js';
import { downloadBytes, slug } from './export.js';

export const REPORT_TITLE = 'AVNI · result report';
export const REPORT_MODEL = 'AVNI-VL 0.9';
export const REPORT_BUILD = 'SIH 26167 · SAC/ISRO';
/** The note the footer carries, in the words the operator asked for. */
export const REPORT_NOTE = 'Generated by SatQuery AI';

// The characters CP1252 carries outside Latin-1. Em dashes and curly quotes live
// here: filtering on "code point <= 0xFF" turned every one of them into a
// question mark in the middle of a sentence.
const CP1252_EXTRAS = new Set(
  '\u20ac\u201a\u0192\u201e\u2026\u2020\u2021\u02c6\u2030\u0160\u2039\u0152\u017d\u2018\u2019\u201c\u201d\u2022\u2013\u2014\u02dc\u2122\u0161\u203a\u0153\u017e\u0178'
);

const GLYPH_TRANSLITERATION = [
  ['ΔT', 'dT'],
  ['−', '-'], // U+2212 minus: the answer bank writes negative dB with it
  ['‑', '-'],
  ['σ', 'sigma'],
  ['Σ', 'Sigma'],
  ['δ', 'delta'],
  ['Δ', 'delta'],
  ['≈', '~'],
  ['≥', '>='],
  ['≤', '<='],
  ['→', '->'],
  ['↔', '<->'],
  ['√', 'sqrt'],
  ['⁻', '-'],
  ['⁰', '0'],
  ['¹', '1'],
  ['✓', 'v'],
  ['✗', 'x'],
  ['⁄', '/']
];

/**
 * WinAnsi-safe text. Anything CP1252 cannot carry is transliterated, and any
 * remaining non-Latin-1 character becomes "?" rather than throwing inside the
 * font encoder (which would lose the whole export).
 */
export function sanitize(value) {
  let s = String(value ?? '');
  for (const [from, to] of GLYPH_TRANSLITERATION) s = s.split(from).join(to);
  // code-point filter rather than a character-class regex: the class would need
  // control characters in it just to keep the newlines the layout relies on
  let out = '';
  for (const ch of s) out += ch.codePointAt(0) <= 0xff || CP1252_EXTRAS.has(ch) ? ch : '?';
  return out;
}

/** "MG Road 0.4 km NE · Bengaluru" — the place line the header shows. */
const aoiPlace = (centroid) => {
  const p = placeSummary(centroid.lat, centroid.lon);
  return p.region ? `${p.short} · ${p.region}` : p.short;
};

const isoDay = (d) => d.toISOString().replace('T', ' ').replace(/\.\d+Z$/, ' UTC');
const dayOnly = (v) => (v ? String(v).replace('T', ' ').replace(/\.\d+Z?$/, 'Z') : null);

export const reportFilename = (question) => `avni_report_${slug(question || 'result')}.pdf`;
/** The geometry file this report cross-references, same slug as the export. */
export const geojsonFilename = (question) => `avni_answer_${slug(question || 'result')}.geojson`;

/**
 * Everything the document prints, as data. Kept separate from the drawing code
 * so a test can assert that each value on the page came from the payload.
 */
export function buildReportModel({
  payload,
  query = null,
  geo,
  centroid = null,
  aoiPoints = [],
  scenes = [],
  raster = null,
  snapshot = null,
  snapshotNote = null,
  now = new Date()
} = {}) {
  const georef = isGeoreferenced(geo);
  const conf = payload?.confidence || {};
  const pc = payload?.physics_check || {};
  const g = payload?.geodetic || {};
  const utm = georef && centroid ? utmBlock(centroid.lat, centroid.lon) : null;
  const aoiKm2 = georef && aoiPoints.length > 2 ? aoiAreaKm2(aoiPoints, geo) : null;
  const aoiHa = georef && aoiPoints.length > 2 ? aoiAreaHa(aoiPoints, geo) : null;

  const header = [
    {
      label: 'area of interest',
      value: georef && centroid ? aoiPlace(centroid) : 'scene not georeferenced',
      mono: false
    },
    {
      label: 'AOI centroid',
      value: georef && centroid ? `${fmtLat(centroid.lat)} ${fmtLon(centroid.lon)}` : 'coordinates withheld',
      mono: true
    },
    { label: 'query raised', value: query?.at ? isoDay(new Date(query.at)) : 'not recorded for this session', mono: true },
    { label: 'session', value: `${REPORT_MODEL} · ${REPORT_BUILD}`, mono: false }
  ];

  const sceneRows = scenes.map((s) => ({
    role: s.role,
    file: s.file || 'unnamed',
    detail: [s.sensor, s.label].filter(Boolean).join(' · '),
    acquired: s.acquired ? dayOnly(s.acquired) : 'acquisition date not reported in the file'
  }));

  const verification = [
    { label: 'consistency score', value: conf.consistency_score != null ? Number(conf.consistency_score).toFixed(2) : 'not reported' },
    { label: 'gate', value: conf.abstained ? `declined — below ${ABSTAIN_GATE}` : `passed — at or above ${ABSTAIN_GATE}` },
    { label: 'reason', value: conf.reason || 'not reported' }
  ];

  const physics = [
    { label: 'NDWI', value: pc.ndwi != null ? `${Number(pc.ndwi).toFixed(2)} (water gate 0.45)` : 'not reported' },
    {
      label: 'SAR backscatter',
      value: pc.sar_backscatter_db != null ? `${Number(pc.sar_backscatter_db).toFixed(1)} dB` : 'not reported'
    },
    { label: 'verdict', value: pc.verdict || 'not reported' },
    { label: 'flag', value: pc.flagged ? 'flagged — readings disagree' : 'clear' }
  ];

  const geodetic = georef
    ? [
        { label: 'CRS', value: geo.crs || 'not stated' },
        { label: 'AOI area', value: aoiHa != null ? `${aoiHa.toFixed(1)} ha (${aoiKm2.toFixed(2)} km²)` : 'no AOI ring drawn' },
        { label: 'AOI vertices', value: aoiPoints.length ? `${aoiPoints.length}` : 'none' },
        { label: 'footprint area (fixture)', value: g.area_ha != null ? `${Number(g.area_ha).toFixed(1)} ha` : 'not reported' },
        { label: 'UTM', value: utm ? `${utm.zone} · ${utm.easting_m.toFixed(0)} E ${utm.northing_m.toFixed(0)} N` : 'not reported' },
        {
          label: 'footprint width',
          value: (() => {
            const { widthKm, heightKm } = extentKm(geo.extent);
            return `${widthKm.toFixed(2)} km x ${heightKm.toFixed(2)} km`;
          })()
        },
        { label: 'ground sample distance', value: raster?.width > 0 ? gsdLabel(geo.extent, raster) : 'not reported — the scene did not declare a raster size' },
        { label: 'georeference', value: geo.source || 'not stated' }
      ]
    : [];

  return {
    title: REPORT_TITLE,
    note: REPORT_NOTE,
    now,
    generatedAt: isoDay(now),
    generatedLabel: `${REPORT_MODEL} · ${REPORT_BUILD}`,
    header,
    scenes: sceneRows,
    question: payload?.question || 'no question recorded',
    intent: payload?.intent || null,
    answer: {
      abstained: !!conf.abstained,
      text: payload?.answer_text || null,
      gate: ABSTAIN_GATE,
      reason: conf.reason || null
    },
    verification,
    physics,
    physicsNote: `${PROVENANCE.fixture.physics_check} · scale and marker positions derived`,
    geodetic: { withheld: !georef, rows: geodetic, reason: georef ? null : withheldGeodetic(geo) },
    trace: (payload?.trace || []).map((t, i) => ({ n: i + 1, step: t.step, source: t.source, value: t.value || null })),
    snapshot,
    snapshotNote: snapshot
      ? snapshot.caption
      : snapshotNote || 'map snapshot unavailable — no decodable scene on screen when the report was composed',
    geojson: georef
      ? { filename: geojsonFilename(payload?.question), withheld: false }
      : { filename: null, withheld: true, reason: 'no geometry written — scene is not georeferenced' }
  };
}

// ------------------------------------------------------------------ */
// page composition
// ------------------------------------------------------------------ */

const A4 = { w: 595.28, h: 841.89 };
const MARGIN = { top: 56, bottom: 62, left: 52, right: 52 };
const INK = [0.11, 0.12, 0.14];
const MUTED = [0.42, 0.45, 0.49];
const RULE = [0.78, 0.79, 0.81];
const ACCENT = [0.05, 0.36, 0.42];

const gray = (rgb, [r, g, b]) => rgb(r, g, b);

const wrapText = (text, font, size, width) => {
  const paragraphs = String(text ?? '').split(/\n/);
  const lines = [];
  for (const para of paragraphs) {
    const words = sanitize(para).split(/\s+/).filter(Boolean);
    if (!words.length) {
      lines.push('');
      continue;
    }
    let line = '';
    for (const word of words) {
      const next = line ? `${line} ${word}` : word;
      if (font.widthOfTextAtSize(next, size) <= width) line = next;
      else {
        if (line) lines.push(line);
        line = word;
      }
    }
    if (line) lines.push(line);
  }
  return lines;
};

class Report {
  constructor(doc, fonts, now) {
    this.doc = doc;
    this.f = fonts;
    this.now = now;
    this.pages = [];
    this.newPage();
  }

  newPage() {
    this.page = this.doc.addPage([A4.w, A4.h]);
    this.pages.push(this.page);
    this.y = A4.h - MARGIN.top;
    this.w = A4.w - MARGIN.left - MARGIN.right;
    return this.page;
  }

  need(height) {
    if (this.y - height < MARGIN.bottom) this.newPage();
  }

  text(str, { font = 'body', size = 10, color = INK, x = MARGIN.left, gap = 0, width = this.w } = {}) {
    const f = this.f[font];
    for (const line of wrapText(str, f, size, width)) {
      this.need(size * 1.35);
      this.page.drawText(line, { x, y: this.y - size, size, font: f, color: gray(this.rgb, color) });
      this.y -= size * 1.35;
    }
    this.y -= gap;
  }

  rule({ color = RULE, thickness = 0.6, gap = 8 } = {}) {
    this.need(thickness + gap);
    this.page.drawLine({
      start: { x: MARGIN.left, y: this.y - thickness },
      end: { x: A4.w - MARGIN.right, y: this.y - thickness },
      thickness,
      color: gray(this.rgb, color)
    });
    this.y -= thickness + gap;
  }

  heading(str) {
    this.need(30);
    this.y -= 6;
    this.text(str, { font: 'bold', size: 12.5, color: INK, gap: 3 });
    this.rule({ gap: 9 });
  }

  subheading(str) {
    this.need(20);
    this.y -= 2;
    this.text(str, { font: 'bold', size: 10.5, color: MUTED, gap: 3 });
  }

  /**
   * Label / value rows — the shape most of this document takes. Values are
   * monospaced when they are numbers or coordinates, per the console's own
   * treatment of data.
   */
  rows(items) {
    const labelW = this.w * 0.34;
    for (const row of items) {
      const valueFont = this.f[row.mono === false ? 'body' : 'mono'];
      const size = row.mono === false ? 10 : 9.5;
      const lines = wrapText(row.value, valueFont, size, this.w - labelW);
      this.need(lines.length * size * 1.4 + 6);
      const top = this.y;
      const wrappedLabel = wrapText(row.label, this.f.body, 9.5, labelW - 8);
      wrappedLabel.forEach((line, i) => {
        this.page.drawText(line, {
          x: MARGIN.left,
          y: top - 9.5 - i * 12,
          size: 9.5,
          font: this.f.body,
          color: gray(this.rgb, MUTED)
        });
      });
      lines.forEach((line, i) => {
        this.page.drawText(line, {
          x: MARGIN.left + labelW,
          y: top - size - i * size * 1.4,
          size,
          font: valueFont,
          color: gray(this.rgb, row.color || INK)
        });
      });
      const block = Math.max(wrappedLabel.length * 12, lines.length * size * 1.4);
      this.y = top - block - 5;
    }
  }

  numbered(items) {
    for (const item of items) {
      const size = 9.5;
      const first = wrapText(item.step, this.f.body, size, this.w - 24);
      const second = item.value ? wrapText(item.value, this.f.mono, 9, this.w - 24) : [];
      const sourceLines = wrapText(item.source || '', this.f.mono, 8.5, this.w - 24);
      this.need((first.length + second.length + sourceLines.length) * size * 1.4 + 8);
      const top = this.y;
      this.page.drawText(`${item.n}.`, {
        x: MARGIN.left,
        y: top - size,
        size,
        font: this.f.mono,
        color: gray(this.rgb, MUTED)
      });
      let cursor = top;
      for (const line of first) {
        this.page.drawText(line, { x: MARGIN.left + 18, y: cursor - size, size, font: this.f.body, color: gray(this.rgb, INK) });
        cursor -= size * 1.4;
      }
      for (const line of sourceLines) {
        this.page.drawText(line, { x: MARGIN.left + 18, y: cursor - 8.5, size: 8.5, font: this.f.mono, color: gray(this.rgb, MUTED) });
        cursor -= 8.5 * 1.4;
      }
      for (const line of second) {
        this.page.drawText(line, { x: MARGIN.left + 18, y: cursor - 9, size: 9, font: this.f.mono, color: gray(this.rgb, ACCENT) });
        cursor -= 9 * 1.4;
      }
      this.y = cursor - 4;
    }
  }

  async image(bytes, { caption = null, maxHeight = 300, mediaType = 'image/png' } = {}) {
    const img =
      mediaType === 'image/jpeg' ? await this.doc.embedJpg(bytes) : await this.doc.embedPng(bytes);
    const width = this.w;
    const height = Math.min(maxHeight, (img.height / img.width) * width);
    this.need(height + 18);
    this.page.drawImage(img, { x: MARGIN.left, y: this.y - height, width, height });
    this.page.drawRectangle({
      x: MARGIN.left,
      y: this.y - height,
      width,
      height,
      borderWidth: 0.6,
      borderColor: gray(this.rgb, RULE),
      color: undefined
    });
    this.y -= height + 12;
    if (caption) this.text(caption, { font: 'italic', size: 8.5, color: MUTED, gap: 4 });
  }

  /** Footer on every page, drawn last so it can count the pages. */
  finish() {
    const total = this.pages.length;
    this.pages.forEach((page, i) => {
      page.drawLine({
        start: { x: MARGIN.left, y: MARGIN.bottom - 18 },
        end: { x: A4.w - MARGIN.right, y: MARGIN.bottom - 18 },
        thickness: 0.6,
        color: gray(this.rgb, RULE)
      });
      page.drawText(sanitize(this.noteLine), {
        x: MARGIN.left,
        y: MARGIN.bottom - 32,
        size: 8,
        font: this.f.body,
        color: gray(this.rgb, MUTED)
      });
      const label = `page ${i + 1} of ${total}`;
      page.drawText(label, {
        x: A4.w - MARGIN.right - this.f.mono.widthOfTextAtSize(label, 8),
        y: MARGIN.bottom - 32,
        size: 8,
        font: this.f.mono,
        color: gray(this.rgb, MUTED)
      });
    });
  }
}

/**
 * Compose the document. Returns the PDF bytes; the caller decides what to do
 * with them (the app downloads them, the tests inspect them).
 */
export async function buildReportPdf(model) {
  const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib');
  const doc = await PDFDocument.create();
  doc.setTitle(sanitize(`${REPORT_TITLE} — ${model.question}`));
  doc.setAuthor(REPORT_NOTE.replace('Generated by ', ''));
  doc.setSubject(sanitize(model.question));
  doc.setCreator('AVNI');
  doc.setProducer(`AVNI · ${REPORT_MODEL}`);
  doc.setCreationDate(model.now);

  const fonts = {
    body: await doc.embedFont(StandardFonts.TimesRoman),
    bold: await doc.embedFont(StandardFonts.TimesRomanBold),
    italic: await doc.embedFont(StandardFonts.TimesRomanItalic),
    mono: await doc.embedFont(StandardFonts.Courier),
    monoBold: await doc.embedFont(StandardFonts.CourierBold)
  };

  const r = new Report(doc, fonts, model.now);
  r.rgb = rgb;
  r.noteLine = `${REPORT_NOTE} · ${REPORT_TITLE} · ${model.generatedLabel}`;

  // 1. header block
  r.text(model.title, { font: 'bold', size: 17, gap: 2 });
  r.text(`generated ${model.generatedAt} · ${model.generatedLabel}`, { font: 'mono', size: 8.5, color: MUTED, gap: 6 });
  r.rule({ gap: 12 });
  r.rows(model.header);

  r.heading('Imagery');
  if (model.scenes.length) {
    model.scenes.forEach((s) => {
      r.rows([{ label: s.role, value: s.file }]);
      r.text(`${s.detail ? `${s.detail} · ` : ''}acquired ${s.acquired}`, { font: 'mono', size: 8.5, color: MUTED, gap: 5 });
    });
  } else {
    r.text('no scene registered', { font: 'body', size: 10, color: MUTED });
  }

  // 2. the question and the answer, as prose
  r.heading('Question & answer');
  r.text(model.question, { font: 'bold', size: 11.5, gap: 6 });
  if (model.answer.abstained) {
    r.text(`DECLINED TO ANSWER — consistency below the ${model.answer.gate} gate.`, { font: 'bold', size: 10.5, color: [0.55, 0.35, 0.05], gap: 4 });
    if (model.answer.reason) r.text(model.answer.reason, { gap: 4 });
    r.text('AVNI ran the full pass but held the answer at the gate.', { color: MUTED, gap: 4 });
  } else {
    r.text(model.answer.text || 'no answer text recorded', { size: 10.5, gap: 4 });
  }

  // 3. confidence and the physics check
  r.heading('Confidence & Verification');
  r.rows(model.verification);
  r.subheading('Physics check');
  r.rows(model.physics);
  r.text(model.physicsNote, { font: 'italic', size: 8.5, color: MUTED, gap: 4 });

  // 4. geodetic evidence, with the map snapshot the report is self-contained on
  r.heading('Geodetic Evidence');
  if (model.geodetic.withheld) {
    r.text(`coordinates withheld — ${model.geodetic.reason?.source || 'scene is not georeferenced'}`, {
      font: 'bold',
      size: 10,
      color: [0.55, 0.35, 0.05],
      gap: 4
    });
    r.text('No lat/lon, area or UTM figure is printed for a scene whose own metadata carries no CRS.', { gap: 4 });
  } else {
    r.rows(model.geodetic.rows);
    r.text(PROVENANCE.derived.aoi_area, { font: 'italic', size: 8.5, color: MUTED, gap: 4 });
  }
  if (model.snapshot?.bytes) {
    await r.image(model.snapshot.bytes, {
      caption: model.snapshotNote,
      mediaType: model.snapshot.mediaType || 'image/png'
    });
  }
  else r.text(model.snapshotNote, { font: 'italic', size: 8.5, color: MUTED, gap: 6 });

  // 5. the trace, numbered: what makes the report auditable
  r.heading('Execution Trace');
  if (model.trace.length) {
    r.numbered(model.trace);
    r.text(`${model.trace.length} steps · sources and values as shown in the execution trace panel`, {
      font: 'italic',
      size: 8.5,
      color: MUTED,
      gap: 4
    });
  } else {
    r.text('no trace recorded for this answer', { color: MUTED });
  }

  // 6. cross-reference to the geometry export
  r.rule({ gap: 10 });
  r.text(
    model.geojson.withheld
      ? `Geometry cross-reference: not written — ${model.geojson.reason}`
      : `Geometry cross-reference: ${model.geojson.filename}`,
    { font: 'mono', size: 8.5, color: MUTED, gap: 2 }
  );

  r.finish();
  return doc.save();
}

/**
 * The app-side entry point: snapshot in, downloaded file out. The caller owns
 * the snapshot (it needs the live viewer), so a report still composes when the
 * snapshot could not be taken — it says so instead of failing.
 */
export async function exportAnswerPDF({
  payload,
  query = null,
  geo,
  centroid = null,
  aoiPoints = [],
  scenes = [],
  raster = null,
  snapshot = null,
  snapshotNote = null,
  now = new Date()
}) {
  const model = buildReportModel({ payload, query, geo, centroid, aoiPoints, scenes, raster, snapshot, snapshotNote, now });
  const bytes = await buildReportPdf(model);
  const filename = reportFilename(payload?.question);
  downloadBytes(bytes, filename, 'application/pdf');
  return { filename, model };
}
